#!/usr/bin/env node
/**
 * Inject the quality-report HTML fragment into docs/index.html.
 * Inserted right before the `<!-- ── Pillar 3: Design style` marker
 * (i.e., right after the vs-datasets section ends).
 *
 * Idempotent — if the report is already injected (marker found), it replaces it.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const FRAG = path.join(ROOT, 'data', 'output', 'quality_report', 'report-fragment.html');
const HTML = path.join(ROOT, 'docs', 'index.html');

const MARKER_BEGIN = '<!-- ──── QR:BEGIN (auto-generated by scripts/quality/inject-report.js) ──── -->';
const MARKER_END   = '<!-- ──── QR:END ──── -->';
const INSERT_BEFORE = '<!-- ── Pillar 3: Design style';

const fragment = fs.readFileSync(FRAG, 'utf8');
let html = fs.readFileSync(HTML, 'utf8');

// 1) Remove any previous injection
if (html.includes(MARKER_BEGIN)) {
  const re = new RegExp(MARKER_BEGIN.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&') + '[\\s\\S]*?' + MARKER_END.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&'), 'g');
  html = html.replace(re, '');
  console.log('Removed previous QR injection');
}

// 2) Inject before the marker
const block = `\n${MARKER_BEGIN}\n${fragment}\n${MARKER_END}\n\n`;
const idx = html.indexOf(INSERT_BEFORE);
if (idx < 0) {
  console.error('FATAL: insertion marker not found:', INSERT_BEFORE);
  process.exit(1);
}
html = html.slice(0, idx) + block + html.slice(idx);

fs.writeFileSync(HTML, html, 'utf8');
console.log(`Injected ${(fragment.length / 1024).toFixed(1)} KB at position ${idx} of docs/index.html`);
console.log(`New docs/index.html size: ${(html.length / 1024).toFixed(1)} KB`);
